# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Controladores.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.avanco = QtWidgets.QPushButton(self.centralwidget)
        self.avanco.setGeometry(QtCore.QRect(10, 400, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.avanco.setFont(font)
        self.avanco.setObjectName("avanco")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 330, 47, 13))
        self.label.setObjectName("label")
        self.InfoAtual = QtWidgets.QLabel(self.centralwidget)
        self.InfoAtual.setGeometry(QtCore.QRect(150, 330, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InfoAtual.setFont(font)
        self.InfoAtual.setObjectName("InfoAtual")
        self.GraficoAnterior = PlotWidget(self.centralwidget)
        self.GraficoAnterior.setGeometry(QtCore.QRect(150, 360, 1201, 311))
        self.GraficoAnterior.setObjectName("GraficoAnterior")
        self.Setpoint = QtWidgets.QSpinBox(self.centralwidget)
        self.Setpoint.setGeometry(QtCore.QRect(70, 330, 61, 22))
        self.Setpoint.setMinimum(-400)
        self.Setpoint.setMaximum(400)
        self.Setpoint.setObjectName("Setpoint")
        self.Voltar = QtWidgets.QPushButton(self.centralwidget)
        self.Voltar.setGeometry(QtCore.QRect(10, 240, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Voltar.setFont(font)
        self.Voltar.setObjectName("Voltar")
        self.InfoAnterior = QtWidgets.QLabel(self.centralwidget)
        self.InfoAnterior.setGeometry(QtCore.QRect(150, 680, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InfoAnterior.setFont(font)
        self.InfoAnterior.setObjectName("InfoAnterior")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setLineWidth(1)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.GraficoAtual = PlotWidget(self.centralwidget)
        self.GraficoAtual.setGeometry(QtCore.QRect(150, 10, 1201, 311))
        self.GraficoAtual.setObjectName("GraficoAtual")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(130, 0, 16, 801))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.PID = QtWidgets.QPushButton(self.centralwidget)
        self.PID.setGeometry(QtCore.QRect(10, 500, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PID.setFont(font)
        self.PID.setObjectName("PID")
        self.PD = QtWidgets.QPushButton(self.centralwidget)
        self.PD.setGeometry(QtCore.QRect(10, 450, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PD.setFont(font)
        self.PD.setObjectName("PD")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addAction(self.actionSalvar)
        self.menubar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Controladores de posição"))
        self.avanco.setText(_translate("MainWindow", "Avanço de fase"))
        self.label.setText(_translate("MainWindow", "Setpoint:"))
        self.InfoAtual.setText(_translate("MainWindow", "TextLabel"))
        self.Voltar.setText(_translate("MainWindow", "Voltar"))
        self.InfoAnterior.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "Controladores"))
        self.PID.setText(_translate("MainWindow", "PID"))
        self.PD.setText(_translate("MainWindow", "PD"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionAbrir.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
        self.actionSalvar.setShortcut(_translate("MainWindow", "Ctrl+S"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

